Refactor developers
Chasseur-de-Succes/CDS-BOT pull request #129
Opened 2024-03-19 19:54 UTC by 0xN0x

- Retrait des ID des développeurs du fichiers config en faveur des variables d'environnements
- Retrait en passant du cpuStats inutilisé depuis plus d'un an dans la commande Info.

2024-03-19 23:32 UTC, rick-gnous requested changes

2024-03-19 23:32 UTC, rick-gnous commented on slash_commands/info.js
> +                { name: 'Développeur', value: developers },
Peut-être profiter pour rajouter un s ?

2024-03-19 23:32 UTC, rick-gnous commented on slash_commands/info.js
> +            .setFooter({ text: 'Demandé par ' + interaction.user.username});
Mélange de `'` et `"`, je pense que ce serait mieux de reprendre ce que tu as fait pour les importations en n'utilisant que `"` (comme la typo, autant en profiter pour refactor un peu le code)

2024-03-19 23:35 UTC, 0xN0x commented on slash_commands/info.js
> +            .setFooter({ text: 'Demandé par ' + interaction.user.username});
Effectivement j'ai pas refactor la commande ni passé le linter mais c'est mieux de passer toutes les chaines en `"` quand c'est possible et le reste en backtick lorsqu'il y a des variables utilisées

2024-03-19 23:36 UTC, 0xN0x commented on slash_commands/info.js
> +                { name: 'Développeur', value: developers },
```suggestion
                { name: 'Développeurs', value: developers },
```

2024-03-19 23:39 UTC, rick-gnous commented on slash_commands/info.js
> +            .setFooter({ text: 'Demandé par ' + interaction.user.username});
On garde ça de côté pour le passage du linter dans ce cas

2024-03-19 23:41 UTC, rick-gnous approved these changes

2024-03-19 23:42 UTC, 0xN0x commented on slash_commands/info.js
> +            .setFooter({ text: 'Demandé par ' + interaction.user.username});
Oups j'ai commit avant de voir ton commentaire, ça fera un peu d'avance tant pis

2024-03-19 23:43 UTC, rick-gnous approved these changes

2024-03-20 22:03 UTC, rick-gnous commented on slash_commands/info.js
> +            if (dev) developers += `- ${dev.tag}\n`
Il n'y a pas moyen de récupérer un utilisateur via son ID dans Discord, avec la méthode [`fetch()`](https://discord.js.org/docs/packages/discord.js/main/User:Class#fetch) de discordjs ? cela permettra d'éviter de faire sauter des devs s'ils ne sont pas sur le serveur

2024-03-20 22:17 UTC, 0xN0x commented on slash_commands/info.js
> +            if (dev) developers += `- ${dev.tag}\n`
Non, si il n'est pas dans les serveurs commun avec le bot, impossible pour le bot de récupérer des infos sur l'utilisateur (sinon on pourrait énumérer tous les utilisateurs de Discord ce qui est un soucis)

2024-03-20 22:20 UTC, 0xN0x commented on slash_commands/info.js
> +            if (dev) developers += `- ${dev.tag}\n`
Ce que `fetch()` fait c'est qu'il va regarder dans le cache si il trouve l'utilisateur, et si non il va passer par l'API de discord pour le récupérer dans les utilisateurs connus

2024-03-20 22:26 UTC, rick-gnous commented on slash_commands/info.js
> +            if (dev) developers += `- ${dev.tag}\n`
tant pis, au pire on réadaptera la fonction dans le futur

2024-03-20 22:31 UTC, rick-gnous commented on slash_commands/info.js
> +            if (dev) developers += `- ${dev.tag}\n`
si ça mange pas de pain, pourquoi pas l'utiliser directement, sinon je pense qu'on a encore assez de marge avant qu'on arrête de tout mettre en cache

2024-03-20 23:01 UTC, merged