Send stacktrace
Chasseur-de-Succes/CDS-BOT pull request #189
Opened 2024-11-07 23:06 UTC by Kekwel

A chaque erreur catché lors d'une interaction ou unhandledRejection ou uncaughtException, un message est envoyé dans le channel logs du serveur Discodeur

2024-11-08 18:34 UTC, rick-gnous requested changes

2024-11-08 18:34 UTC, rick-gnous commented on util/util.js
il faut revert ce changement pour éviter d'avoir des erreurs

2024-11-08 19:26 UTC, Kekwel commented on util/util.js
Ah punaise j’étais persuadé d’avoir fait attention avec le jsonValue mais pas assez.. je revert dès que possible

2024-11-08 21:21 UTC, Kekwel commented on util/util.js
C'est le `this` qui pose soucis ?

2024-11-09 09:44 UTC, rick-gnous approved these changes

2024-11-09 09:47 UTC, rick-gnous commented
peut-être rajouter le channel dans le fichier de configuration ?

2024-11-11 22:29 UTC, Kekwel commented
oui on pourrait, j'avais oublié que le bot est sur 2 serveurs actuellement

2024-11-14 21:34 UTC, merged