Event tower #185
Chasseur-de-Succes/CDS-BOT pull request #191
Opened 2024-11-08 21:43 UTC by Kekwel

cf #185

2024-11-12 18:55 UTC, rick-gnous requested changes
peut-être demander une revue de plus, la PR est lourde et je pense que je suis passé à côté d'un ou deux trucs

2024-11-12 18:55 UTC, rick-gnous commented on slash_commands/subcommands/tower/valider-jeu.js
> +}
est-ce que ce ne serait pas intéressant de le mettre dans une fonction à part ? à voir si cela peut-être plus utile pour éviter le code boilerplate

2024-11-12 18:55 UTC, rick-gnous commented on slash_commands/subcommands/tower/valider-jeu.js
> +    if (!userDb) {
plutôt faire un !== None ou quelque chose comme ça ? je ne sais pas si ça peut faire des cas non voulus avec la forme actuelle

2024-11-12 18:55 UTC, rick-gnous commented on slash_commands/subcommands/tower/valider-jeu.js
> +
on ne peut pas configurer via une commande slash pour remonter cette erreur sans faire du code en plus ?

2024-11-12 18:55 UTC, rick-gnous commented on slash_commands/subcommands/tower/valider-jeu.js
> +        const damage = 1; // modifiable ?
limite mettre ça en const globale ou en env pour pouvoir modifier facilement la valeur

2024-11-12 18:55 UTC, rick-gnous commented on events/ready.js
> +        }
pas de préfix

2024-11-12 18:55 UTC, rick-gnous commented on index.js
pourquoi tout migrer de ce fichier ?

2024-11-12 20:49 UTC, Kekwel commented on CHANGELOG.md
Ca me va !

2024-11-12 20:51 UTC, Kekwel commented on events/messageCreate.js
comme dit sur discord, je vais passer en `/admin tower`

2024-11-12 20:53 UTC, Kekwel commented on index.js
C'était principalement pour continuer ce qui était fait, avoir un fichier pour chaque event, et ClientReady en est un

2024-11-12 20:53 UTC, Kekwel commented on models/eventBoss.js
en effet, oubli de ma part de renommer en plus de cela

2024-11-12 20:54 UTC, Kekwel commented on prefix/tower/tower.js
comme dit sur discord, et + haut, je vais passer en `/admin tower`

2024-11-12 20:56 UTC, Kekwel commented on slash_commands/subcommands/tower/valider-jeu.js
> +}
oui totalement d'accord, dans un fichier util ?
après j'ai fait comme ca pour éviter d'avoir trop de `new EmbedBuilder()` partout

2024-11-12 21:05 UTC, Kekwel commented on slash_commands/subcommands/tower/valider-jeu.js
> +    if (!userDb) {
Je crois pas que None existe en JS, mais la condition fonctionne, si `client.getUser(author)` ne trouve pas l'utilisateur dans la bdd, ca retourne rien (donc `undefined`) donc `userDb` est `undefined`, cf exemple dans la console :
![image](https://github.com/user-attachments/assets/60b7d303-a1c9-454b-b50a-da0f6408cfab)

2024-11-12 21:11 UTC, Kekwel commented on slash_commands/subcommands/tower/valider-jeu.js
> +
j'ai pas compris sur quoi tu veux configurer.
Mais en gros, la commande accepte soit un appid directement, soit l'appid en sélectionnant le jeu parmis un Select permettant de chercher par nom. On accepte les 2 arguments mais ils ne sont pas requis, c'est un test si aucun des deux n'est renseigné

2024-11-12 21:12 UTC, Kekwel commented on slash_commands/tower.js
> +                .addIntegerOption((option) =>
si, cf l'autocomplete, le string permet de chercher le nom du jeu, et une fois sélectionné, l'appid (integer) est retourné

2024-11-12 23:12 UTC, rick-gnous commented on slash_commands/tower.js
> +                .addIntegerOption((option) =>
habile bill

2024-11-12 23:12 UTC, rick-gnous commented on index.js
c'est bon pour moi du coup, je n'avais en effet pas fait le lien, oups

2024-11-12 23:20 UTC, rick-gnous commented on slash_commands/subcommands/tower/valider-jeu.js
> +}
oui, `utils/embed.js` par ex., à voir cependant si c'est vraiment utile avec le reste du code, mais ça permettrait de simplifier la gestion des embed. on peut en faire un ticket mais c'est pas prio sur cette pr

2024-11-12 23:20 UTC, rick-gnous commented on slash_commands/subcommands/tower/valider-jeu.js
> +
oui en effet, vu comme ça, ça fait sens

2024-11-13 22:12 UTC, rick-gnous requested changes
deux petits à modifier ou à m'expliquer parce que je n'ai pas bien compris

2024-11-13 22:14 UTC, rick-gnous commented
je rajoute #139 vu que tu as bougé les commandes shops, on s'occupera de bouger les dernières commandes dans une autre PR

2024-11-13 22:57 UTC, Kekwel commented on events/messageCreate.js
oh mon mauvais

2024-11-13 22:58 UTC, Kekwel commented on package-lock.json
arrr j'ai du le mettre sans faire attention dans mon commit, désolé

2024-11-14 21:41 UTC, Kekwel commented on events/messageCreate.js
ou pas ? https://stackoverflow.com/a/44210813

2024-11-14 21:42 UTC, Kekwel commented on package-lock.json
ou pas ? https://stackoverflow.com/a/44210813

2024-11-14 21:45 UTC, rick-gnous commented on package-lock.json
on le mettra à jour avec le packages.json. on garde le même environnement pour l'instant, et la mise à jour se fera dans une autre branche

2024-11-14 21:47 UTC, Kekwel commented on package-lock.json
ok je revert du coup

2024-11-14 22:21 UTC, merged